[package]
name = "inference-tests"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
wasmtime="47.0.3"

inference-analysis.workspace = true
inference-ast.workspace = true
inference-hassert.workspace = true
inference-parser.workspace = true
inference-wasm-codegen.workspace = true
inference-wasm-to-v-translator.workspace = true
inference-type-checker = { workspace = true, features = ["test-utils"] }
inference.workspace = true
inf-wasmparser.workspace = true
rustc-hash.workspace = true
wasmprinter = "0.245.1"

[dev-dependencies]
cov-mark = { workspace = true, features = ["enable"] }
sha2 = "0.11"
tempfile = "3"
wasmparser = "0.245.1"
wat = "1.225.0"
