use crate::utils::{build_ast, get_test_data_path};
use inference::LinkOptions;
use inference::wasm_link::driver::resolve_external_modules;
use inference::wasm_link::resolve::{ModulePath, SearchPath};
use inference_type_checker::TypeCheckerBuilder;
use inference_wasm_codegen::{CompilationMode, OptLevel, Target};
use rustc_hash::FxHashMap;

/// Compiles one fixture under `tests/test_data/inf/` and returns its WASM.
pub(crate) fn compile_fixture(file: &str, module_name: &str, mode: CompilationMode) -> Vec<u8> {
    let path = get_test_data_path().join("inf").join(file);
    let source =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let arena = build_ast(source);
    let typed_context = TypeCheckerBuilder::build_typed_context(arena)
        .unwrap_or_else(|e| panic!("type check failed for {file}: {e}"))
        .typed_context();
    inference_wasm_codegen::codegen(
        &typed_context,
        module_name,
        inference_wasm_codegen::CodegenOptions {
            target: Target::Wasm32,
            mode,
            opt_level: OptLevel::O3,
            features: inference_wasm_codegen::EmitFeatures::default(),
            layout: inference_wasm_codegen::MemoryLayout::default(),
        },
    )
    .unwrap_or_else(|e| panic!("codegen failed for {file}: {e}"))
    .wasm()
    .to_vec()
}

/// Proof-mode `.v` for one single-file fixture, driven entirely in-process.
pub(crate) fn generate_v(file: &str, module_name: &str) -> String {
    let wasm = compile_fixture(file, module_name, CompilationMode::Proof);
    translate(file, module_name, &wasm)
}

/// Translates a compiled module using its embedded proof metadata.
pub(crate) fn translate(file: &str, module_name: &str, wasm: &[u8]) -> String {
    // Empty explicit maps: the per-spec indices and the hassert obligations
    // both ride along in the embedded `inference.spec_funcs` /
    // `inference.hspecs` custom sections (see ROCQ_CONTRACT.md). For a
    // linked module they are also the only correct source — the linker
    // rewrote the embedded indices into the post-merge space, leaving
    // codegen's own record stale.
    let empty: FxHashMap<String, Vec<u32>> = FxHashMap::default();
    let empty_hspecs = inference::HSpecMap::default();
    inference::wasm_to_v(module_name, wasm, &empty, &empty_hspecs)
        .unwrap_or_else(|e| panic!("wasm_to_v failed for {file}: {e}"))
}

/// Where a linked external's `.wasm` comes from.
///
/// The two arms answer different questions and neither subsumes the other.
/// A fixture-built external keeps the gate self-contained — regenerate it by
/// editing Inference source — but every instruction in it came out of the
/// same emitter as the main module, so it can only ever restate what a
/// single-file fixture already covers. A committed artifact is the only way
/// to put a *foreign* compiler's instruction selection in front of `coqc`,
/// which is the thing the linker envelope exists for, and the price is that
/// its bytes are regenerated by hand.
#[derive(Debug, PartialEq, Eq)]
pub(crate) enum ExternalBytes {
    /// Compiled here from an Inference fixture under `tests/test_data/inf/`.
    Fixture {
        /// The fixture whose own compilation produces the bytes.
        source: &'static str,
        /// The module name the external is compiled under — deliberately not
        /// the logical module, so a confusion between the two cannot pass:
        /// the merged body's symbol tracks the binding, not the external's
        /// own name for itself.
        module_name: &'static str,
        /// How the library itself was compiled. It is a property of the
        /// library and not of the link: a library compiled for execution
        /// carries no verification sections at all, so only a proof-mode one
        /// has obligations of its own for an adopting entry to carry across.
        mode: CompilationMode,
    },
    /// Read from a committed `.wasm` under `tests/test_data/wasmlib/`, built
    /// by a toolchain that is not this compiler. That directory's `README.md`
    /// records which one and how to regenerate the bytes.
    Artifact {
        /// File name under `tests/test_data/wasmlib/`.
        file: &'static str,
    },
}

/// One external `.wasm` a linked fixture merges: the logical module its
/// `use … from` clause names, and where its bytes come from.
#[derive(Debug, PartialEq, Eq)]
pub(crate) struct LinkedExternal {
    /// The name the main fixture's `use … from` clause binds against, and
    /// the key the linker merges under.
    pub(crate) logical_module: &'static str,
    pub(crate) bytes: ExternalBytes,
}

impl LinkedExternal {
    /// The external's `.wasm`, built or read according to its source.
    fn wasm(&self) -> Vec<u8> {
        match self.bytes {
            ExternalBytes::Fixture {
                source,
                module_name,
                mode,
            } => compile_fixture(source, module_name, mode),
            ExternalBytes::Artifact { file } => {
                let path = get_test_data_path().join("wasmlib").join(file);
                std::fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
            }
        }
    }
}

/// Proof-mode `.v` for a fixture that links external `.wasm` modules,
/// running the same steps a real `infc -L` build does: resolve each external
/// through the compiler driver, compile the main fixture, statically merge
/// under the declarations' write-set contracts, and translate the *merged*
/// module.
///
/// The merge is what makes an obligation about an `external fn` resolvable
/// at all: before it the external is an import, and an import carries no
/// body for the downstream realization obligation to reduce.
///
/// The externals go through [`resolve_external_modules`], not straight into
/// the linker, so every gate a production build applies to a library applies
/// here: signature validation of each bound declaration against the `.wasm`,
/// and the **checked** write-set mode, under which a merged body that stores
/// through a parameter its declaration did not mark `mut` is refused. A
/// producer that handed the bytes over unchecked could publish a selected
/// artifact for a link `infc` rejects, and a companion proof would then
/// certify an artifact no user can build.
///
/// `options` carries what the merge does with the verification sections a
/// library ships. It is a caller's own input rather than a constant here
/// because it decides what the translated module *contains*: under the default
/// the merged module states only the program's own obligations, and under
/// adoption it also states the library's, keyed under the logical module.
///
/// This is the one linked generator in the crate. The `coqc` corpus gate and
/// the selected-artifact discharge export both call it, so a linked `.v` the
/// gate elaborates and the same fixture's committed golden cannot be produced
/// by two subtly different pipelines.
pub(crate) fn generate_linked_v(
    file: &str,
    module_name: &str,
    externals: &[LinkedExternal],
    options: &LinkOptions,
) -> String {
    // The driver resolves a logical module to `<dir>/<segments>.wasm`, so each
    // external is laid out under a search directory the way `-L` expects.
    let lib_dir = tempfile::tempdir().expect("create a library search directory");
    for external in externals {
        let relative = ModulePath::from_segments(external.logical_module.split("::"))
            .unwrap_or_else(|e| panic!("{}: {e}", external.logical_module))
            .to_relative_path();
        let target = lib_dir.path().join(relative);
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent)
                .unwrap_or_else(|e| panic!("create {}: {e}", parent.display()));
        }
        std::fs::write(&target, external.wasm())
            .unwrap_or_else(|e| panic!("write {}: {e}", target.display()));
    }

    let path = get_test_data_path().join("inf").join(file);
    let source =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let typed_context = TypeCheckerBuilder::build_typed_context(build_ast(source))
        .unwrap_or_else(|e| panic!("type check failed for {file}: {e}"))
        .typed_context();
    let mut search_path = SearchPath::new();
    search_path.push_lib_dir(lib_dir.path().to_path_buf());
    let resolved = resolve_external_modules(&typed_context, &search_path, None)
        .unwrap_or_else(|e| panic!("resolving the externals of {file} failed: {e}"));

    let main = compile_fixture(file, module_name, CompilationMode::Proof);
    let linked = inference::link_with_options(
        &main,
        &resolved.module_bytes(),
        Some(&resolved.contracts),
        options,
    )
    .unwrap_or_else(|e| panic!("link failed for {file}: {e}"))
    .wasm;
    translate(file, module_name, &linked)
}
