[package]
name = "inference-wasm-to-v-translator"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
inf-wasmparser.workspace = true
inference-fn-key.workspace = true
inference-hassert.workspace = true
inference-wasm-codegen.workspace = true
rustc-hash.workspace = true
thiserror.workspace = true

[dev-dependencies]
wat = "1.225.0"
