[package]
name = "inference-wasm-codegen"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
wasm-encoder.workspace = true
inference-ast.workspace = true
inference-type-checker.workspace = true
inference-fn-key.workspace = true
inference-hassert.workspace = true
anyhow.workspace = true
rustc-hash.workspace = true
cov-mark.workspace = true
thiserror.workspace = true

[dev-dependencies]
inf-wasmparser.workspace = true
inference-compiler-interface.workspace = true
inference-parser.workspace = true
inference-type-checker = { workspace = true, features = ["test-utils"] }
wasmprinter = "0.254.0"
tempfile = "3"
cov-mark = { workspace = true, features = ["enable"] }
