[package]
name = "inference-wasm-codegen"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
wasm-encoder = "0.245.1"
inference-ast.workspace = true
inference-type-checker.workspace = true
anyhow.workspace = true
rustc-hash.workspace = true
cov-mark.workspace = true
thiserror.workspace = true

[dev-dependencies]
inf-wasmparser.workspace = true
inference-type-checker = { workspace = true, features = ["test-utils"] }
wasmprinter = "0.245.1"
cov-mark = { workspace = true, features = ["enable"] }
