[package]
name = "inference-lsp"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
description = "Inference Language Server Protocol implementation"

[[bin]]
name = "inference-lsp"
path = "src/main.rs"

[dependencies]
lsp-server = "=0.8.0"
lsp-types = "=0.97.0"
serde_json.workspace = true
anyhow.workspace = true
rustc-hash.workspace = true
inference-ide.workspace = true
