name: Build & Test (Main)

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'book/**'

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      release-build: false
      package-artifacts: false
