name: Build Compiler Book (PR)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'book/**'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.3

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: ./book
          file: ./book/Dockerfile
          push: false
