name: Build & Test (PR)

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'book/**'

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      release-build: false
      package-artifacts: false
